networks:
  iex:
    external: true

version: '3.8'

services:
  # PHP-FPM Service
  php-fpm:
    container_name: ${PROJECT_NAME}_php
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./.env:/var/www/html/.env
    expose:
      - "9000"
    networks:
      - iex

  # NGINX Service
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./.env:/var/www/html/.env
    ports:
      - "${APP_EXTERNAL_PORT:-80}:80"
    depends_on:
      - php-fpm
    networks:
      - iex

  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: 'mysql:8.3.0'
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    networks:
      - iex

  phpmyadmin:
    container_name: ${PROJECT_NAME}_phpmyadmin
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PROJECT_NAME}_mysql
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_EXTERNAL_PORT}:80
    networks:
      - iex

volumes:
  mysql_data:
    driver: local